### ISSUE TITLE
On "The farthest point strategy for progressive image sampling"

### ISSUE THREAD

**Issue by WhatAShot** [Ryan-Zirui-Wang/farthest-point-sampling#3]
There are many papers on FPS, and the methods for 1D and 2D images are discussed in "The farthest point strategy for progressive image sampling". But this repo is about 3D images, is there any relationship between this repo and "The farthest point strategy for progressive image sampling"?

**Comment by ziruiw-dev** [comment]
This is just a 3D implementation in point cloud domain. In this FPS algorithm, using pixel coordinates is identical to using 3D point coordinates to me.
